### ISSUE TITLE
login options

### ISSUE THREAD

**Issue by finwo** [trackthis/js-api-client#15]
To ensure we have more control over which login methods we're using, we should allow the code that's using this library enable or disable certain methods. 

This would also allow us to use the API client on the oauth login page & disabling oauth in this lib, so we don't redirect to the oauth page AGAIN.

**Comment by finwo** [comment]
@wahibsaif Please don't randomly close issues if any merged pull request belongs to it... The merged pull request might not be the fix, so more might follow.

**Comment by wahibsaif** [comment]
@finwo noted. but I guess we closed it together Last Thursday?
